#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define MENU_H 100
#define WINDOW_W 750
#define WINDOW_H 500 + MENU_H

enum {ZOZOR, LAURENT, NICOLAS, XAVIER, THOMAS, VIDE};
enum {EASY, MODERATE, HARD, IMPOSSIBLE};

#endif // CONSTANTES_H_INCLUDED
